### ISSUE TITLE
ala-like prefix for ale

### ISSUE THREAD

**Issue by nathgit** [ae-dschorsaanjo/nasin-pi-jan-Sotan#3]
Have you considered a prefix for ale/ali like what is used for 'ala'? it would make it easy then to say 'everybody' like you can say 'nobody' (ajan?). Maybe 'u/ul' since it isn't being used anywhere else? 'uljan' could be 'everybody', or something similar.

**Comment by nathgit** [comment]
I thought of using u/ul as a prefix for ale/ali, just replacing the a with u so 'everybody' would be u'jan (أین or أُیَن) everything would be ulijo (أُلِیۆ/ألیۆ). I personally write it using the arabic alphabet because I think it's a good fit & I like the look. The ' is kind of equivalent to ئ (hamza) or glottal stop which is common in Arabic.

**Comment by ae-dschorsaanjo** [comment]
The "informal" part of the doc is there solely for archiving purposes, so that I have a reference on how I used non-standard language in the past. I do not plan expanding it, even if it would change, it would remain the same, but with more properly written descriptions.

If you feel like expanding that, feel free to fork it, I'm gonna change the license for this whole thing to CC-BY.
